import { notFound } from "next/navigation";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { customers, products, quotes } from "@/lib/demo/data";
import { calculatePrice } from "@/lib/pricing/engine";
import { formatCurrency } from "@/lib/utils";
export default async function QuoteDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const quote = quotes.find((item) => item.id === id); if (!quote) notFound(); const customer = customers.find((c) => c.id === quote.customerId); const product = products.find((p) => p.id === quote.productId)!; const calc = calculatePrice({ quoteId: quote.id, productId: quote.productId, answers: quote.answers, selectedLimit: quote.selectedLimit, selectedDeductible: quote.selectedDeductible, userId: quote.ownerUserId }); return <AppShell title={`Preventivo ${quote.id}`} breadcrumb="Preventivo / dettaglio"><div className="grid gap-5"><Card><CardHeader title="Riepilogo" action={<Badge tone={quote.status.includes("REFERRAL") ? "amber" : "green"}>{quote.status}</Badge>} /><div className="grid gap-3 md:grid-cols-4"><p><strong>Cliente</strong><br />{customer?.displayName}</p><p><strong>Prodotto</strong><br />{product.name}</p><p><strong>Massimale</strong><br />{formatCurrency(quote.selectedLimit)}</p><p><strong>Premio lordo</strong><br />{formatCurrency(calc.result.grossPremium)}</p></div><div className="mt-5 flex flex-wrap gap-3"><Button>Genera proposta PDF</Button><Button variant="secondary">Invia proposta</Button><Button variant="outline">Payment link mock</Button></div></Card><Card><CardHeader title="Tab: questionario / pricing trace / documenti / pagamenti / referral / audit" /><pre className="overflow-auto rounded-2xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(calc.trace, null, 2)}</pre></Card></div></AppShell>; }
